package entity;
// Generated Nov 19, 2024 5:22:21 PM by Hibernate Tools 3.6.0



/**
 * TbKaryawan generated by hbm2java
 */
public class TbKaryawan  implements java.io.Serializable {


     private TbKaryawanId id;
     private String namaKaryawan;
     private String usiaKaryawan;
     private String statusKaryawan;

    public TbKaryawan() {
    }

    public TbKaryawan(TbKaryawanId id, String namaKaryawan, String usiaKaryawan, String statusKaryawan) {
       this.id = id;
       this.namaKaryawan = namaKaryawan;
       this.usiaKaryawan = usiaKaryawan;
       this.statusKaryawan = statusKaryawan;
    }

    public TbKaryawan(String nik, String nama, int usia, String statusKaryawan) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public TbKaryawanId getId() {
        return this.id;
    }
    
    public void setId(TbKaryawanId id) {
        this.id = id;
    }
    public String getNamaKaryawan() {
        return this.namaKaryawan;
    }
    
    public void setNamaKaryawan(String namaKaryawan) {
        this.namaKaryawan = namaKaryawan;
    }
    public String getUsiaKaryawan() {
        return this.usiaKaryawan;
    }
    
    public void setUsiaKaryawan(String usiaKaryawan) {
        this.usiaKaryawan = usiaKaryawan;
    }
    public String getStatusKaryawan() {
        return this.statusKaryawan;
    }
    
    public void setStatusKaryawan(String statusKaryawan) {
        this.statusKaryawan = statusKaryawan;
    }

    public void setNama(String nama) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setUsia(int usia) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


